filebeat.inputs:
- type: filestream
  id: default-filestream
  paths:
    - ingest_data/*.log

setup.kibana:
  host: ${KIBANA_HOSTS}
  username: ${ELASTIC_USER}
  password: ${ELASTIC_PASSWORD}

output.logstash:
  hosts: ${LOGSTASH_HOSTS}
  